### ISSUE TITLE
系统环境变量

### ISSUE THREAD

**Issue by Hunlongyu** [markthree/dnrm#1]
![image](https://github.com/markthree/dnrm/assets/15273630/467e142e-6986-4706-96c4-0d9f814019d5)
安装成功，根据提示，添加到环境变量里：
![image](https://github.com/markthree/dnrm/assets/15273630/6543bc8e-3032-49c5-8f9e-97f9f090b718)
但是后面的 set PATH=%PATH%;C:\Users\Hunlongyu\.deno\bin 是啥？没管它，结果无法正常运行。
![image](https://github.com/markthree/dnrm/assets/15273630/f7503b2e-7fc5-4994-87a5-7fdad90a70ec)

但我进入脚本目录下，是可以正常运行的。
![image](https://github.com/markthree/dnrm/assets/15273630/47f61ae0-7100-4aac-845d-5530f7ac7daa)
所以是我系统的环境变量没有加全嘛？还是缺少了什么步骤？

**Comment by markthree** [comment]
@Hunlongyu 靓仔你好，重启你的电脑试试

**Comment by Hunlongyu** [comment]
好像重启后可以。
